apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
  # labels:
  #   app: sidecar-demo
spec:
  # replicas: 1
  # selector:
  #   matchLabels:
  #     app: sidecar-demo
  # template:
  #   metadata:
  #     labels:
  #       app: sidecar-demo
    # Logging container. A simple script that writes current CPU usage to a log file every ten seconds
  containers:   
    - name: main-app
      image: ubuntu:jammy-20220801
      command: ["/bin/sh"]
      args: ["-c", "while true; do date && vmstat -s | grep 'used memory' >> memory-info.txt && vmstat -s | grep 'free memory' >> memory-info.txt; sleep 10; done"]
      volumeMounts:
      - name: shared-volume
        mountPath: /var/log
    - name: helper-app
      image: nginx:1.14.2
      ports:
      - containerPort: 80
      volumeMounts:
      - name: shared-volume
        mountPath: /usr/share/nginx/html
        readOnly: true 
  volumes:
  - name: shared-volume
    emptyDir: {}
