apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:   
        - name: main-app
          image: kimschles/nodejs-server:1.1.0
          volumeMounts:
          - name: shared-volume
            mountPath: /var/log
        - name: helper-app
          image: ubuntu:jammy-20220801
          command: ["/bin/sh"]
          args: ["-c", "while true; do cat /var/log/access.log; sleep 60; done"]
          volumeMounts:
          - name: shared-volume
            mountPath: /var/log
      volumes:
      - name: shared-volume
        emptyDir: {}
